services:
  storage:
    storage-account:
      kind: StorageV2
      httpsOnly: true
      sku: Standard_LRS
      cors:
      - services:
        - blob
        methods:
        - OPTIONS
        - PUT
        origins:
        - "*"
        allowedHeaders:
        - "*"
        exposedHeaders:
        - "*"
      containers:
        images:
          publicAccess: blob
        thumbnails:
          publicAccess: blob
  analyzer:
    cognitiveservices-account:
      kind: ComputerVision
      sku: F0
  image-data:
    cosmosdb:
      databases:
        imagesdb:
          collections:
            images:
              throughput: 400
  functions:
    functionapp:
      storageAccount: data
      authentication:
        enabled: true
        action: azureActiveDirectoryLogin
        tokenStore: true
        redirectUris:
        - $(webapp:primaryEndpoint)
      settings:
        AZURE_STORAGE_CONNECTION_STRING: $(storage:connectionString)
        COMP_VISION_KEY: $(analyzer:key1)
        COMP_VISION_URL: $(analyzer:url)
        COSMOSDB_CONNECTION_STRING: $(image-data:connectionString)
      cors:
      - $(webapp:primaryEndpoint)
      # postdeploy:
      # npm init -y
      # npm install --save axios azure-storage jimp
      functions:
        GetImages:
          source: csharp/GetImages
        GetUploadUrl:
          source: csharp/GetUploadUrl
        ResizeImage:
          source: csharp/ResizeImage
        # GetImages:
        #   source: javascript/GetImages
        # GetUploadUrl:
        #   source: javascript/GetUploadUrl
        # ResizeImage:
        #   source: javascript/ResizeImage
  webapp:
    static-website:
      host: storage
      source: www
      build:
        requires:
        - node@lts
        commands:
        - npm install
        - npm run generate
        output: www/dist
      substitutions:
      - settings.js
      index: index.html
