services:
  backingStore:
    storageAccount:
      kind: StorageV2
      httpsOnly: true
      sku: Standard_LRS
      cors:
      - services:
        - blob
        methods:
        - OPTIONS
        - PUT
        origins:
        - "*"
        allowedHeaders:
        - "*"
        exposedHeaders:
        - "*"
      containers:
        images:
          publicAccess: blob
        thumbnails:
          publicAccess: blob
  analyzer:
    cognitiveservices-account:
      kind: ComputerVision
      sku: F0
  imageData:
    cosmosdb:
      databases:
        imagesdb:
          collections:
            images:
              throughput: 400
  functions:
    functionapp:
      storageAccount: backingStore
      authentication:
        enabled: true
        action: azureActiveDirectoryLogin
        tokenStore: true
        redirectUris:
        - $(frontend:primaryEndpoint)
      settings:
        AZURE_STORAGE_CONNECTION_STRING: $(backendStore:connectionString)
      cors:
      - $(frontend:primaryEndpoint)
      postDeploy:
      - npm init -y
      - npm install --save axios azure-storage jimp
      functions:
        GetImages:
          source: javascript/GetImages
        GetUploadUrl:
          source: javascript/GetUploadUrl
        ResizeImage:
          source: javascript/ResizeImage
  frontend:
    storageWebsite:
      host: backingStore
      source: www
      build:
        requires:
        - node >= lts
        commands:
        - npm install
        - npm run generate
        output: www/dist
      settings:
        authEnabled:  true
      index: index.html
