apiVersion: 1.0
kind: terraform
build:
- source: www
  commands:
  - npm install
  - npm run generate
apply:
  module: deployment
  variables:
    resource_group: $(resourceGroup)
    default_location: $(location)
push:
- type: app-service/zip-deploy
  path: ${LANGUAGE:-csharp}
  resource: image_api
- type: storage/web-site
  path: www/dist
  resource: frontend
