apiVersion: 1.0
kind: terraform
build:
- source: www
  commands:
  - npm install
  - npm run generate
apply:
  module: deployment
  variables:
    resource_group: $(resourceGroup)
    default_location: $(location)
push:
- type: app-service/zip-deploy
  path: ${LANGUAGE:-csharp}
  resource: azurerm_function_app.image_api
- type: storage/web-site
  path: www/dist
  replacements:
  - file: settings.template.js
    output: settings.js
  resource: azurerm_storage_static_website.frontend
