services:
  backingStore:
    storageAccount:
      kind: StorageV2
      httpsOnly: true
      sku: Standard_LRS
      cors:
      - services: [blob]
        methods: [OPTIONS, PUT]
        origins: ["*"]
        allowedHeaders: ["*"]
        exposedHeaders: ["*"]
      containers:
      - name: images
        publicAccess: blob
      - name: thumbnails
        publicAccess: blob
  analyzer:
    cognitiveservicesAccount:
      kind: ComputerVision
      sku: F0
  imageData:
    cosmosdb:
      databases:
      - name: imagesdb
        collections:
        - name: images
          throughput: 400
  functions:
    functionapp:
      storageAccount: backingStore
      authentication:
        enabled: true
        action: azureActiveDirectoryLogin
        tokenStore: true
        redirectUris:
        - $(frontend:primaryEndpoint)
      cors:
        allowedOrigins:
        - $(frontend:primaryEndpoint)
      settings:
        AZURE_STORAGE_CONNECTION_STRING: $(backendStore:connectionString)
      postDeploy:
      - npm init -y
      - npm install --save axios azure-storage jimp
      functions:
      - name: GetImages
        source: javascript/GetImages
      - name: GetUploadUrl
        source: javascript/GetUploadUrl
      - name: ResizeImage
        source: javascript/ResizeImage
  frontend:
    staticWebsite:
      account: backingStore
      source: www
      build:
        requires:
        - node >= lts
        commands:
        - npm install
        - npm run generate
        output: www/dist
      settings:
        authEnabled: true
      index: index.html
