services:
  images:
    storageContainer:
      publicAccess: blob
  thumbnails:
    storageContainer:
      publicAccess: blob
  imageDocuments:
    cosmosdbCollection:
      name: images
      database:
      - name: imagesdb
      throughput: 400
  analyzer:
    cognitiveservicesAccount:
      kind: ComputerVision
      sku: F0
  functions:
    functionapp:
      authentication:
        enabled: true
        action: azureActiveDirectoryLogin
        appDisplayName: First Serverless Web Application
        tokenStore: true
        redirectUris:
        - $(frontend:primaryEndpoint)
  GetImages:
    requires: imageDocuments!
    function:
      app: functions
      source: csharp/GetImages
  GetUploadUrl:
    requires: images!
    function:
      app: functions
      source: csharp/GetUploadUrl
  ResizeImage:
    requires: [images!, thumbnails!, imageDocuments!, analyzer!]
    function:
      app: functions
      source: csharp/ResizeImage
  frontend:
    requires: [images, functions]
    staticWebsite:
      content: www/dist
      settings:
        authEnabled: true
      index: index.html
endpoints:
  frontend: $(frontend:primaryEndpoint)
