services:
  images:
    storageContainer:
      publicAccess: blob
  thumbnails:
    storageContainer:
      publicAccess: blob
  imageDocuments:
    cosmosdbCollection:
      name: images
      database:
      - name: imagesdb
      throughput: 400
  analyzer:
    cognitiveservicesAccount:
      kind: ComputerVision
      sku: F0
  apiHost:
    functionapp:
      authentication:
        enabled: true
        action: azureActiveDirectoryLogin
        appDisplayName: First Serverless Web Application
        tokenStore: true
        redirectUris:
        - $(frontend:primaryEndpoint)
      source: javascript/site
  GetImages:
    requires: imageDocuments!
    function:
      app: apiHost
      source: javascript/GetImages
  GetUploadUrl:
    requires: images!
    function:
      app: apiHost
      source: javascript/GetUploadUrl
  ResizeImage:
    requires: [images!, thumbnails!, imageDocuments!, analyzer!]
    function:
      app: apiHost
      source: javascript/ResizeImage
  frontend:
    requires: [images, apiHost]
    staticWebsite:
      content: www/dist
      settings:
        authEnabled: true
      index: index.html
endpoints:
  frontend: $(frontend:primaryEndpoint)
