services:
  backingStore:
    storageAccount:
      kind: StorageV2
      httpsOnly: true
      sku: Standard_LRS
      cors:
      - services: [blob]
        methods: [OPTIONS, PUT]
        origins: ["*"]
        allowedHeaders: ["*"]
        exposedHeaders: ["*"]
  images:
    storageContainer:
      account: backingStore
      publicAccess: blob
  thumbnails:
    storageContainer:
      account: backingStore
      publicAccess: blob
  imageDocuments:
    cosmosdbCollection:
      name: images
      database:
      - name: imagesdb
      throughput: 400
  analyzer:
    cognitiveservicesAccount:
      kind: ComputerVision
      sku: F0
  functions:
    functionapp:
      storageAccount: backingStore
      authentication:
        enabled: true
        action: azureActiveDirectoryLogin
        tokenStore: true
        redirectUris:
        - $(frontend:primaryEndpoint)
      cors:
        allowedOrigins:
        - $(frontend:primaryEndpoint)
      postDeploy:
      - npm init -y
      - npm install --save axios azure-storage jimp
  GetImages:
    requires: imageDocuments
    function:
      app: functions
      source: javascript/GetImages
  GetUploadUrl:
    requires: images
    function:
      app: functions
      source: javascript/GetUploadUrl
  ResizeImage:
    requires: [backingStore, imageDocuments, analyzer]
    function:
      app: functions
      source: javascript/ResizeImage
  frontend:
    requires: functions
    staticWebsite:
      account: backingStore
      source: www/dist
      settings:
        authEnabled: true
      index: index.html
endpoints:
  frontend:
  - primaryEndpoint