services:
  frontend:
    staticWebsite:
      requires:
        +functionApp:
        images:
          methods: [GET, PUT]
      content: www/dist
      settings:
        authEnabled: true
      index: index.html
  +functionApp:
    authentication:
      activeDirectory:
        appDisplayName: First Serverless Web Application
      tokenStore: true
      redirectTo: frontend
  GetImages:
    function:
      requires: imageMetadata!
      source: csharp/GetImages
  GetUploadUrl:
    function:
      requires: images!
      source: csharp/GetUploadUrl
  ResizeImage:
    function:
      requires: [images!, thumbnails!, analyzer!, imageMetadata!]
      source: csharp/ResizeImage
  images:
    storageContainer:
      publicAccess: blob
  thumbnails:
    storageContainer:
      publicAccess: blob
  analyzer:
    computerVision:
  imageMetadata:
    cosmosDBCollection:
      name: images
      database:
      - name: imagesdb
      throughput: 400
