services:
  frontend:
    staticWebsite:
      requires: [+functionapp, images]
      content: www/dist
      settings:
        authEnabled: true
      index: index.html
  +functionapp:
    authentication:
      activeDirectory:
        appDisplayName: First Serveless Web Application
      tokenStore: true
      redirectTo: frontend
  GetImages:
    function:
      requires: imageMetadata!
      source: csharp/GetImages
  GetUploadUrl:
    function:
      requires: images!
      source: csharp/GetUploadUrl
  ResizeImage:
    function:
      requires: [images!, thumbnails!, analyzer!, imageMetadata!]
      source: csharp/ResizeImage
  images:
    storageContainer:
      publicAccess: blob
  thumbnails:
    storageContainer:
      publicAccess: blob
  analyzer:
    cognitiveservices:
      kind: ComputerVision
      pricingTier: F0
  imageMetadata:
    cosmosdbCollection:
      name: images
      database:
      - name: imagesdb
      throughput: 400
