services:
  images:
    storageContainer:
      publicAccess: blob
  thumbnails:
    storageContainer:
      publicAccess: blob
  imageDocuments:
    cosmosdbCollection:
      name: images
      database:
      - name: imagesdb
      throughput: 400
  analyzer:
    cognitiveservicesAccount:
      kind: ComputerVision
      sku: F0
  functions:
    functionapp:
      authentication:
        enabled: true
        action: azureActiveDirectoryLogin
        appDisplayName: First Serverless Web Application
        tokenStore: true
        redirectUris:
        - $(frontend:primaryEndpoint)
      source: javascript/site
  GetImages:
    requires: imageDocuments
    function:
      app: functions
      source: javascript/GetImages
  GetUploadUrl:
    requires: images
    function:
      app: functions
      source: javascript/GetUploadUrl
  ResizeImage:
    requires: [backingStore, imageDocuments, analyzer]
    function:
      app: functions
      source: javascript/ResizeImage
  frontend:
    requires:
      images: primaryEndpoint
      functions: true
    staticWebsite:
      content: www/dist
      settings:
        authEnabled: true
      index: index.html
endpoints:
  frontend: $(frontend:primaryEndpoint)
