name: first-serverless-app
imports:
- azure
services:
  myfrontend:
    type: storage.website
    requires:
      mybackend.GetImages:
      mybackend.GetUploadUrl:
      mybackend.images:
        methods: [GET, PUT]
    content: www/dist
    settings:
      authEnabled: true
    index: index.html
  mybackend:
    services:
      GetImages:
        type: httpFunction
        tags: requiresAuth
        parameters:
        - source: imageMetadata
          query: select * from c order by c._ts desc
      GetUploadUrl:
        type: httpFunction
        tags: requiresAuth
      images:
        type: storage.container
        publicAccessLevel: blob
      thumbnails:
        type: storage.container
        publicAccessLevel: blob
      analyzer:
        type: cognitive.vision
      imageMetadata:
        type: cosmosDB.collection
        name: images
        database:
        - name: imagesdb
        throughput: 400
