name: first-serverless-app
imports:
- azure
services:
  myfrontend:
    type: storage.website
    requires:
      mybackend.myfunctions:
      mybackend.images:
        methods: [GET, PUT]
    content: www/dist
    settings:
      authEnabled: true
    index: index.html
  mybackend:
    services:
      myfunctions:
        type: function.app
        default: true
        authentication:
          activeDirectory:
            appDisplayName: First Serverless Web Application
          tokenStore: true
          redirectTo: myfrontend
      GetImages:
        type: function
        requires: imageMetadata!
        source: csharp/GetImages
      GetUploadUrl:
        type: function
        requires: images!
        source: csharp/GetUploadUrl
      ResizeImage:
        type: function
        requires: [images!, thumbnails!, analyzer!, imageMetadata!]
        source: csharp/ResizeImage
      images:
        type: storage.container
        publicAccessLevel: blob
      thumbnails:
        type: storage.container
        publicAccessLevel: blob
      analyzer:
        type: cognitive.vision
      imageMetadata:
        type: cosmosDB.collection
        name: images
        database:
        - name: imagesdb
        throughput: 400
