name: first-serverless-app
imports:
- azure
services:
  frontend:
    type: storage.website
    requires:
      backend.functions:
      backend.images:
        methods: [GET, PUT]
    content: www/dist
    settings:
      authEnabled: true
    index: index.html
  backend:
    services:
      functions:
        type: function.app
        default: true
        authentication:
          activeDirectory:
            appDisplayName: First Serverless Web Application
          tokenStore: true
          redirectTo: frontend
      GetImages:
        type: httpFunction
        requires: imageMetadata!
        source: csharp/GetImages
      GetUploadUrl:
        type: httpFunction
        requires: images!
        source: csharp/GetUploadUrl
    images:
      type: storage.container
      publicAccessLevel: blob
      triggers:
        put:
        - requires: [images!, thumbnails!, analyzer!, imageMetadata!]
          source: csharp/ResizeImage
    thumbnails:
      type: storage.container
      publicAccessLevel: blob
    analyzer:
      type: cognitive.computerVision
    imageMetadata:
      type: cosmosDB.collection
      name: images
      database:
      - name: imagesdb
      throughput: 400
scripts:
- cloud-compose.js
