#!/bin/bash

NAME_default_functionApp=default-$(hash functionApp/default@$LOCATION)
APP=$(az ad app list --identifier-uri "https://$NAME_default_functionApp.azurewebsites.net" --query '[].{a:appId,d:displayName}' -o tsv)
if [ -n "$APP" ]; then
  APP_ID=$(echo $APP | cut -d' ' -f1)
  DISPLAY_NAME=$(echo $APP | cut -d' ' -f2-)
  echo Deleting Azure Active Directory application \'$DISPLAY_NAME\'...
  az ad app delete --id $APP_ID
fi
