#!/bin/bash
mkdir -p ~/bin
MD=$(cd $(dirname "$BASH_SOURCE") && pwd -P)
ln -fs "$MD/az" ~/bin/az
ln -fs "$MD/az-compose" ~/bin/az-compose
ln -fs "$MD/az-up" ~/bin/az-up
if [ -z "$(which az-compose)" ]; then
  echo >> ~/.bashrc
  echo 'PATH="$HOME/bin:$HOME/.local/bin:$PATH"' >> ~/.bashrc
  export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
fi
