services:
  backingStore:
    storageAccount:
      kind: StorageV2
      httpsOnly: true
      sku: Standard_LRS
      cors:
      - services: [blob]
        methods: [OPTIONS, PUT]
        origins: ["*"]
        allowedHeaders: ["*"]
        exposedHeaders: ["*"]
  images:
    storageContainer:
      account: backingStore
      publicAccess: blob
  thumbnails:
    storageContainer:
      account: backingStore
      publicAccess: blob
  functions:
    functionapp:
      storageAccount: backingStore
      cors:
        allowedOrigins:
        - $(frontend:primaryEndpoint)
  GetUploadUrl:
    requires: images
    function:
      app: functions
      source: csharp/GetUploadUrl
  ResizeImage:
    requires: backingStore
    function:
      app: functions
      source: csharp/ResizeImage
  frontend:
    requires:
      backingStore:
        primaryEndpoints: blob
      functions: true
    staticWebsite:
      account: backingStore
      content: www/dist
      index: index.html
endpoints:
  frontend: $(frontend:primaryEndpoint)
