services:
  backingStore:
    storageAccount:
      kind: StorageV2
      httpsOnly: true
      sku: Standard_LRS
      cors:
      - services: [blob]
        methods: [OPTIONS, PUT]
        origins: ["*"]
        allowedHeaders: ["*"]
        exposedHeaders: ["*"]
  images:
    storageContainer:
      account: backingStore
      publicAccess: blob
  GetUploadUrl:
    requires: images
    function:
      app:
        storageAccount: backingStore
        cors:
          allowedOrigins:
          - $(frontend:primaryEndpoint)
      source: csharp/GetUploadUrl
  frontend:
    requires:
      backingStore:
        primaryEndpoints: blob
      functions: true
    staticWebsite:
      account: backingStore
      content: www/dist
      index: index.html
endpoints:
  frontend: $(frontend:primaryEndpoint)
